name: build

on:
  workflow_run:
    workflows:
      - test
    branches:
      - master
      - push-xvwntqtunnqm
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # TODO: activate this once this repo is public
      #      - name: Generate artifact attestation
      #        uses: actions/attest-build-provenance@v2
      #        with:
      #          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #          subject-digest: ${{ steps.push.outputs.digest }}
      #          push-to-registry: true

      - uses: actions/delete-package-versions@v5
        with:
          package-name: "miffy"
          package-type: 'container'
          min-versions-to-keep: 5